Added docker CI workflow
kubearmor/kubetls pull request #9
Opened 2023-06-25 20:15 UTC by PrimalPimmy

This PR adds two docker release processes:
- Latest: Image is pushed when anything is pushed to the main branch
- Versioned: When a release is created in github, a tag is generated. That same tag is used to publish into dockerhub once released.

NOTE: currently I only added any changes that can be done in the `src` file, but as the project expands this can be updated

2023-06-30 18:34 UTC, nyrahul approved these changes

2023-06-30 18:52 UTC, nyrahul requested changes
There is too much duplication in these two workflows. It is possible to merge the workflows and have two push events. The only other change that happens is the gitref .. we can keep it to main if that simplifies the workflow.

2023-07-02 19:58 UTC, PrimalPimmy commented
I have simplified the workflow now @nyrahul

2023-07-09 16:09 UTC, nyrahul approved these changes
LGTM

2023-07-09 16:09 UTC, merged